export const GlobalNames = {
  sharedPreferencesName: 'RecycEarn',
  keyChainService: 'RecycEarn',
  regions: 'regions',
  token: 'token',
  firebaseToken: 'firebaseToken',
  tempToken: 'tempToken',
  profileInfo: 'profileInfo',
  latLong: 'latLong',
  missionId: 'missionId',
  buyerIsActive: 'buyerIsActive',
  buyerTypeOfTrip: 'buyerTypeOfTrip',
  assignBuyerId: 'assignBuyerId',
  Notification: 'Notification',
};
